# -- DjLint Configurations

# -- Formatter Settings
# Ensure void tags (e.g., <br>, <hr>) are properly closed.
close_void_tags = true

# Limit consecutive blank lines (0 = remove all).
max_blank_lines = 2

# -- Linter Settings
# H005: <html> should have lang attribute
# H006: <img> should have height/width
# H013: <img> should have alt text
# H014: More than 2 blank lines
# H023: Avoid entity references
# H025: Orphan tag warning
# H030: Missing meta description
# H031: Missing meta keywords
ignore = "H005,H006,H013,H014,H023,H025,H030,H031"
